### ISSUE TITLE
Matlab cannot find the add-in

### ISSUE THREAD

**Issue by lmulder1991** [RocketWrench/ZipFile#1]
Issue must be smt obvious. But I don't see what I'm doing wrong. 
++ added the GIT clone to my Matlab local_data folder
++ included the repo inside Matlab Seach Path: _matlabpath([genpath('C:\Localdata\Matlab'),matlabpath])_

but if I run the command _'io.ZipFile()'_ I run into this error. Anyone ran into same problem?
![Screenshot 2022-01-21 113235](https://user-images.githubusercontent.com/88686866/150512161-6ffcc9a6-2d2b-4130-9956-daa1bfe4b3ee.png)

**Comment by RocketWrench** [comment]
Imulder1991

This issue comes from me being new to Github

The folder layout required to run in Matlab is

+io
----@Entry
----@GeneralPurposeBit
----@Zipfile
----+Fields
----+internal
----+Readers

I believe the Git clone does not provide the +io namespace folder

Let me know if this helped

Collin

**Comment by lmulder1991** [comment]
![Screenshot 2022-01-21 21 0212](https://user-images.githubusercontent.com/88686866/150532887-df1a5019-fbab-42f8-a551-2d9f469be0e9.png)
This is how my GIT clone looks right now. If I understood correctly I should rename the foldername from _ZipFile_ to _+io_ ? 

I did that, now it works OK. I'm also not a GIT expert, but why did you rename this folder to _+io_ in the first place?

**Comment by RocketWrench** [comment]
Yes,  all that inside a folder named, +io.  The folder must be on the Matlab path as well

**Comment by RocketWrench** [comment]
I think I fixed it

**Comment by lmulder1991** [comment]
Great!. I'll try again

**Comment by lmulder1991** [comment]
Yes, works fine. Thanks!
